CREATE TABLE IF NOT EXISTS readings (id TEXT PRIMARY KEY NOT NULL,date TEXT NOT NULL,reading TEXT NOT NULL,raw TEXT NOT NULL,first_fetched TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS statuses (id TEXT PRIMARY KEY NOT NULL,status TEXT NOT NULL,updated TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS source_cache (id TEXT PRIMARY KEY NOT NULL,payload TEXT,expires TEXT NOT NULL,modified TEXT,fetched TEXT,retry_after TEXT,error TEXT);
