'use client';
import {useEffect,useState,useCallback,useRef} from 'react';
import {CircleDollarSign,RefreshCw,ArrowUpRight,Database,FlaskConical,ArrowLeftRight,Check,Clock,ExternalLink} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {resetEvaluationState,runFixture} from '@/lib/reading.mjs';
const tests=[['normal-d1-a','1일차 · 100'],['normal-d1-b','같은 날 · 105'],['normal-d2','다음 날 · 120'],['timeout','응답 지연'],['auth-401','접근 거절'],['rate-429','호출 제한'],['offline','오프라인'],['schema-break','형식 변경'],['recover-d2','재시도 · 복구']];
const failures:Record<string,[string,string]>={timeout:['응답이 늦어지고 있어요','잠시 후 다시 시도해 주세요.'],auth:['데이터 원천이 접근을 거절했어요','출처의 접근 정책을 확인한 뒤 다시 시도해 주세요.'],rate_limit:['잠시 쉬어갈게요','호출 제한이 풀린 뒤 다시 시도해 주세요.'],offline:['데이터에 연결할 수 없어요','인터넷 연결을 확인한 뒤 다시 시도해 주세요.'],schema_error:['데이터 형식이 달라졌어요','출처의 응답 형식을 확인해야 합니다.']};
function time(v:string|null){return v?new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',dateStyle:'medium',timeStyle:'medium'}).format(new Date(v)):'—';}
function signed(n:number){return `${n>0?'+':''}${Number(n.toFixed(6)).toLocaleString('ko-KR',{maximumFractionDigits:6})}`;}
export default function Home(){const [live,setLive]=useState<any>(resetEvaluationState);const [demo,setDemo]=useState<any>(resetEvaluationState);const [tab,setTab]=useState('live');const [busy,setBusy]=useState(true);const initialQueryStarted=useRef(false);const [clock,setClock]=useState(Date.now());const [error,setError]=useState('');const [fixtures,setFixtures]=useState<Record<string,any>>({});const [report,setReport]=useState<any[]>([]);
const load=useCallback(async(refresh=false)=>{setBusy(true);setError('');try{const r=await fetch('/api/reading',{method:refresh?'POST':'GET',cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error);setLive(d);return d;}catch(e:any){setError(e.message||'연결에 실패했습니다. 다시 시도해 주세요.');throw e;}finally{setBusy(false);}},[]);
useEffect(()=>{if(initialQueryStarted.current)return;initialQueryStarted.current=true;load(true).catch(()=>{});Promise.all(tests.map(async([id])=>{const r=await fetch(`/t04/fixtures/${id}.json`);if(!r.ok)throw Error('검사 자료를 불러오지 못했습니다. 새로고침해 주세요.');return [id,await r.json()];})).then(a=>setFixtures(Object.fromEntries(a))).catch(e=>setError(e.message));},[load]);
useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const c=new AbortController();Promise.resolve(context.registerTool({name:'refresh_exchange_rate',description:'공개 원천의 달러·원화 환율을 조회하고 오늘 기록을 저장합니다.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:any)=>{if(input&&Object.keys(input).length)throw Error('입력값은 필요하지 않습니다.');const s=await load(true);return {reading:s.current_reading,status:s.status};}},{signal:c.signal})).catch(()=>{});return()=>c.abort();},[load]);
useEffect(()=>{const timer=setInterval(()=>setClock(Date.now()),1000);return()=>clearInterval(timer);},[]);
const cooldown=tab==='live'&&live.retry_at?Math.max(0,Math.ceil((Date.parse(live.retry_at)-clock)/1000)):0;
const state=tab==='live'?live:demo;const current=state.current_reading;const rows=state.daily_readings;const code=state.status?.error_code;const stale=state.status?.freshness==='stale';const last=rows.at(-1);const prev=rows.at(-2);const delta=last&&prev&&last.unit===prev.unit?last.normalized_value-prev.normalized_value:null;
async function replay(id:string){if(!fixtures[id])return;setDemo((s:any)=>runFixture(s,fixtures[id]));}
function allTests(){const results:any[]=[];let s=resetEvaluationState();for(const id of ['normal-d1-a','normal-d1-b','normal-d2']){s=runFixture(s,fixtures[id]);check(id,s);}for(const id of ['timeout','auth-401','rate-429','offline','schema-break']){let b=resetEvaluationState();for(const key of ['normal-d1-a','normal-d1-b',id])b=runFixture(b,fixtures[key]);check(id,b);if(id==='timeout'){b=runFixture(b,fixtures['recover-d2']);check('recover-d2',b);s=b;}}function check(id:string,s:any){const e=fixtures[id].expected;const pass=s.status.freshness===e.freshness&&s.status.error_code===e.error_code&&s.daily_readings.length===e.row_count&&s.current_reading?.normalized_value===e.stored_value&&(e.delta===undefined||s.last_delta===e.delta);results.push({id,label:tests.find(t=>t[0]===id)?.[1],pass,status:s.status,rows:s.daily_readings.length,value:s.current_reading?.normalized_value});}setReport(results);setDemo(s);}
return <main className="shell"><header className="topbar"><a href="/" className="brand"><span className="brandmark"><CircleDollarSign size={23}/></span>하루의 환율</a><span className="topnote">하나의 값, 하루의 기록</span><span className="timezone">KST · Asia/Seoul</span></header><div className="intro"><div><p className="eyebrow">DAILY EXCHANGE JOURNAL</p><h1>1달러, 오늘은 얼마?</h1><p>달러의 원화 환율을 확인하고, 하루의 변화를 기록해요.</p></div><div className="location"><ArrowLeftRight size={18}/>USD → KRW</div></div><Tabs value={tab} onValueChange={setTab}><TabsList className="viewtabs"><TabsTrigger value="live"><CircleDollarSign size={16}/>오늘의 환율</TabsTrigger><TabsTrigger value="demo"><FlaskConical size={16}/>오류·복구 실험실</TabsTrigger></TabsList><TabsContent value="demo"><div className="notice">합성 데이터 전용 공간입니다. 실제 환율과 일별 기록에는 영향을 주지 않아요. 실제 날짜 2일의 증빙을 대신하지 않습니다.</div><section className="lab"><div className="sectionhead"><h2>같은 입력으로, 정확하게 확인하기</h2><button className="secondary" disabled={Object.keys(fixtures).length!==9} onClick={allTests}>9개 시나리오 자동 검사</button></div><div className="testbuttons">{tests.map(([id,label])=><button key={id} disabled={!fixtures[id]} onClick={()=>replay(id)}>{label}</button>)}<button onClick={()=>{setDemo(resetEvaluationState());setReport([]);}}>합성 기록 초기화</button></div>{report.length>0&&<div className="report" aria-live="polite">{report.map(r=><span key={r.id} className={r.pass?'passed':'failed'}>{r.pass?'✓':'✕'} {r.label}</span>)}<small>공식 fixture 9종의 상태·저장 건수·값·변화량 검사입니다. 전체 35개 제출 조건의 통과를 의미하지 않습니다.</small></div>}</section></TabsContent></Tabs>
{tab==='live'&&live.served_from_cache&&<div className="notice">제공처 갱신 전이라 보관 중인 원자료를 사용했어요. 다음 외부 조회 가능 시각: {time(live.cache_expires)}</div>}
{error&&<div className="notice error" role="alert">{error}<button onClick={()=>load().catch(()=>{})}>다시 불러오기</button></div>}
<div className="dashboard"><section className={`temperature ${stale?'stale':''}`}><div className="cardtop"><span>{tab==='live'?'1 미국 달러 (USD)':'합성 시험값'}</span><span className="status">{busy?'조회 중':stale?(current?'오래된 값':'조회 실패'):!current?'조회 전':'정상 수신'}</span></div><div className="temperaturevalue">{current?current.normalized_value.toLocaleString('ko-KR',{maximumFractionDigits:10}):'—'}<span>{current?.unit??'원/USD'}</span></div><p className="readingcaption">{tab==='live'?(current?.source_name??'ExchangeRate-API · 일일 기준 환율'):'ALEPH 공식 합성 데이터 · 실제 환율 아님'}</p><div className="temperaturebottom"><span><Clock size={15}/>{current?time(current.fetched_at):'아직 조회한 기록이 없어요'}</span><button className="refresh" disabled={busy||cooldown>0||(tab==='demo'&&!fixtures['recover-d2'])} onClick={()=>tab==='live'?load(true).catch(()=>{}):replay(stale?'recover-d2':'normal-d1-a')}><RefreshCw size={17} className={busy?'spin':''}/>{busy?'불러오는 중…':cooldown>0?`${cooldown}초 후 재시도`:stale?'다시 시도':'환율 새로 확인'}</button></div></section>
<section className="comparison"><span className="eyebrow">하루의 변화</span><h2>{prev&&last&&new Date(last.record_date).getTime()-new Date(prev.record_date).getTime()===86400000?'어제 기록과 비교':'이전 기록과 비교'}</h2><div className="deltavalue">{delta===null?'—':signed(delta)}<span>{current?.unit??'원/USD'}</span></div><p>{delta===null?'서로 다른 날짜의 기록이 쌓이면 비교할 수 있어요.':`${prev.record_date}의 ${prev.normalized_value}${prev.unit}에서 ${delta>0?'올랐어요':delta<0?'내렸어요':'같아요'}.`}</p><div className="formula">{delta===null?'오늘 기록 − 이전 날짜 기록':`${last.normalized_value} − ${prev.normalized_value} = ${signed(delta)} ${last.unit}`}</div></section></div>
{stale&&failures[code]&&<div className="notice error" role="status"><div><strong>{failures[code][0]}</strong><p>{failures[code][1]} {current?'마지막 정상값은 그대로 보관하고 있어요.':'아직 정상 수신한 값이 없어 환율을 표시할 수 없어요.'}</p><small>{tab==='live'&&live.last_attempt?`마지막 조회 시도: ${time(live.last_attempt)} · `:''}stale / {code}{state.last_run?.retry_after_seconds?` · ${state.last_run.retry_after_seconds}초 뒤 재시도`:''}</small></div></div>}
<section className="details"><div><span>출처</span><a href={tab==='live'?(current?.source_url??'https://www.exchangerate-api.com/'):'/t04/README.md'} target="_blank" rel="noreferrer">{tab==='live'?'ExchangeRate-API':'ALEPH 합성 자료'}<ExternalLink size={13}/></a></div><div><span>출처 시각</span><strong>{time(current?.source_time)}</strong></div><div><span>조회 시각</span><strong>{time(current?.fetched_at)}</strong></div><div><span>기록 기준 시간대</span><strong>Asia/Seoul (UTC+9)</strong></div></section>
<section className="history"><div className="sectionhead"><div><h2>하루에 한 줄</h2><p>같은 날 다시 조회하면 갱신하고, 다음 날에는 새로 기록해요.</p></div><span className="count"><Database size={15}/>{rows.length}일의 기록</span></div>{rows.length===0?<div className="empty"><Database size={28}/><h3>첫 번째 기록을 기다리고 있어요</h3><p>‘환율 새로 확인’을 누르면 오늘의 값이 저장됩니다.</p></div>:<Table><TableHeader><TableRow><TableHead>기록 날짜 · KST</TableHead><TableHead>{tab==='live'?'환율':'시험값'}</TableHead><TableHead>출처 시각</TableHead><TableHead>마지막 조회</TableHead><TableHead>원자료·저장값</TableHead></TableRow></TableHeader><TableBody>{[...rows].reverse().map((r:any)=><TableRow key={r.record_id}><TableCell>{r.record_date}</TableCell><TableCell className="tablevalue">{r.normalized_value} {r.unit}</TableCell><TableCell>{time(r.reading.source_time)}</TableCell><TableCell>{time(r.last_fetched_at)}</TableCell><TableCell><details><summary>상세 보기</summary><pre>{JSON.stringify({record_id:r.record_id,source_observed_at:r.reading.source_time,...r.reading,raw:tab==='live'?live.raw_readings?.find((v:any)=>v.date===r.record_date)?.raw:undefined},null,2)}</pre></details></TableCell></TableRow>)}</TableBody></Table>}</section>
<footer><span>하루의 환율 <b>·</b> 1 USD 기준 · 대한민국 원화</span><a href="https://www.exchangerate-api.com/docs/free" target="_blank" rel="noreferrer">데이터 안내 <ArrowUpRight size={14}/></a></footer><p className="footnote">환율은 하루 단위로 갱신되는 참고값입니다. 은행의 실제 환전 적용 환율이나 수수료를 포함하지 않습니다. 제공처의 다음 갱신 시각까지 원자료를 보관해 사용합니다. 실제 기록은 서버에 저장됩니다. 오류·복구 실험실의 기록은 페이지를 새로 열면 초기화됩니다.</p><p className="footnote"><a href="https://www.exchangerate-api.com" target="_blank" rel="noreferrer">Rates By Exchange Rate API</a> · 원응답에서 USD→KRW 값만 추출하고 시각은 한국 시간으로 표시했습니다.</p><details className="submission"><summary>과제 확인 안내</summary><p>1. 오늘의 환율에서 ‘환율 새로 확인’을 누릅니다. 2. 원자료·저장값 상세에서 값과 두 시각을 확인합니다. 3. 실험실에서 자동 검사를 실행하고 오류 버튼과 다시 시도를 확인합니다.</p><p>정상이면 값·단위·출처·시각과 기록이 표시됩니다. 오류가 나면 마지막 값, 오래된 값 표시, 원인별 안내와 다시 시도가 표시됩니다.</p><p>실제 조회 기록은 아래 표의 원자료와 저장값으로 확인합니다. 교육 플랫폼의 선택 과정 기록은 제출과 승인에 영향을 주지 않습니다. 이 앱은 날짜를 조작하지 않습니다.</p><a href="/t04/criterion-registry.json">전체 35개 기준</a> · <a href="/t04/asset-manifest.json">원본 파일 해시 목록</a> · <a href="/api/source">전체 소스와 커밋 보기</a></details></main>;
}
